---
title: 'Homework #1'
author: "Max Ruehle; mtruehle"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This homework is more or less a tutorial that helps you set up the tools used in this course, and familiarizes you with the format of the submission requirement. 
This homework is **due on Jan 22** before class.

You can use the RMarkDown file with these homework instructions to as a template for your work. 
Make sure to replace "Your Name" and "your_github_username" in the YAML with your name and Github username.

1. Create a folder named `ds202_hw1`, and create an RMarkDown file `hw1.Rmd` under this folder to include your solutions. The file and folder names are *case-sensitive*, which means `hw1.Rmd` and `HW1.rmd` are different. *It is crucial to follow the exact folder structure and file names*, so that your homework can be reproduced and graded by an automated script. 
2. Write a paragraph (<100 words) describing an example of what you consider data science. Write your paragraph in R Markdown. Include at least 
    a. one link to a chart or an image and 
    b. at least one italized or bolded word.
    
    Data science is all about using collected data to make inferences and conclusions about something that relates to the dataset, or the data itself. It is used by data scientists and sometimes computer scientists and engineers to make use of the data and **visualize** it. [This image does a great job of explaining data science.](https://cdn-images-1.medium.com/max/1200/1*mgXvzNcwfpnBawI6XTkVRg.png)
    
3. Install R, and then RStudio. To make sure the installation is correct, find the version of R by entering `version` into the R console. Put this command into a R code trunk to automatically include the R version in your report. 

version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.2                         
year           2018                        
month          12                          
day            20                          
svn rev        75870                       
language       R                           
version.string R version 3.5.2 (2018-12-20)
nickname       Eggshell Igloo       
4. Install git. 
    - If you are on Windows operating system: 
        a. Install [Git for Windows](https://gitforwindows.org/). In particular, we will need to use the Git Bash (not the Git GUI). 
        b. After installation, set up Rstudio to use Git bash as the shell for the Terminal: Open RStudio, click Tools--Global Options--Terminal; under **Shells**, select Git Bash; click OK. 
        c. In the main menu of RStudio: click Tools--Terminal--New Terminal. If you have a `$` before your prompt, then you should have done.
    - If you are on Linux or macOS, Git has probably been correctly configured by default, so nothing needs to be installed. Just click the Terminal tab (above the R Console).
5. What is the version of your Git? To find out, go to the Terminal tab in RStudio (right to the Console tab), and type in the following command. If it works, this shows the setup of your terminal and Git is correct. Then explore the bash command-line and Git.

    ```
    git --version
    ```
    git version 2.20.1.windows.1
    
6. Configure Git by modifying and entering the following commands into the terminal

    ```
    git config user.name "your first and last name"
    git config user.email "yourEmail"
    ```

7. Register a [GitHub](https://www.github.com) account. What is your username?

mtruehle

Now Knit the finished Homework 1 one last time, and you are done! The actual submission (to a GitHub repository) will take place in Lab 1.